name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Snyk Vulnerability Scan
  # You may pin to the exact commit or the version.
  # uses: snyk/actions@7fad562681122205233d1242c3bb39598c5393da
      uses: snyk/actions@0.3.0
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
    # Which Snyk command to run, defaults to test
        command: monitor
    # Additional arguments to pass to Snyk
        #args: --org=
